title: Nina Creates
email: your-email@example.com
description: >
  A passionate, creative hub for comics, photography, writing, and more.
baseurl: "" # leave empty unless your site is in a subfolder
url: "https://nina-creates.github.io"

# Switch to Minimal Mistakes
remote_theme: mmistakes/minimal-mistakes
theme: null

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Optional but recommended:
author:
  name: Nina de Wolfe
